#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2024 Harald Sitter <sitter@kde.org>

if ! /proc/cmdline | grep 'KDEOSLive'; then
    echo "Not running kdeos-live-generator" > /dev/kmsg
    exit 0
fi

ls -lahR /dev/disk > /dev/kmsg

if [ -f /dev/disk/by-label/KDEOSLive ]; then
    echo "Found by label" > /dev/kmsg
fi

