#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2023-2024 Harald Sitter <sitter@kde.org>

build() {
    map add_binary \
        /usr/lib/systemd/systemd-volatile-root \
        /usr/bin/_kdeos-overlay \
        /usr/lib/systemd/system-generators/kdeos-live-generator \
        /usr/lib/systemd/systemd-bootchart

    map add_systemd_unit \
        systemd-volatile-root.service \
        kdeos-overlay.service \
        systemd-bootchart.service
}
