#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2023-2024 Harald Sitter <sitter@kde.org>

build() {
    map add_binary \
        /usr/lib/systemd/systemd-volatile-root \
        /usr/bin/_kde-linux-overlay \
        /usr/bin/_kde-linux-rootfs-transition \
        /usr/lib/systemd/system-generators/kde-linux-live-generator \
        /usr/lib/systemd/system-generators/kde-linux-mount-generator \
        /usr/lib/systemd/systemd-bootchart \
        /usr/bin/btrfs

    map add_systemd_unit \
        systemd-volatile-root.service \
        kde-linux-overlay.service \
        systemd-bootchart.service
}
