# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2025 Nate Graham <nate@kde.org>

command_not_found_handler () {
    _kde-linux-command-not-found-handler.py "$1"
}
